#!/bin/bash
for channel in stable beta nightly; do
    archive=$(curl -fsSL https://static.rust-lang.org/dist/channel-rust-$channel | grep x86_64-unknown-linux-gnu)
    echo "archive: $archive" | mustache /dev/stdin Dockerfile.mustache > $channel/Dockerfile && echo "Done: $channel/Dockerfile"
done
