#!/bin/bash
for channel in stable beta nightly; do
    archive=$(curl -fsSL https://static.rust-lang.org/dist/channel-rust-$channel | grep x86_64-unknown-linux-gnu)

    # render base images
    echo "{rust_home: /rust, archive: $archive}" |
	mustache /dev/stdin Dockerfile.mustache > $channel/Dockerfile &&
	echo "Done: $channel/Dockerfile"

    # render onbuild images
    echo "{app_home: /rust/app, channel: $channel}" |
	mustache /dev/stdin Dockerfile_onbuild.mustache > $channel/onbuild/Dockerfile &&
	echo "Done: $channel/onbuild/Dockerfile"
done
